twitter-auth:
    CONSUMER_KEY: ""
    CONSUMER_SECRET: ""
    ACCESS_TOKEN: ""
    ACCESS_TOKEN_SECRET: ""

neuralspace-nlu-auth:
    MODEL_ID: ""
    ACCESS_TOKEN: ""
    neuralspace_nlu_url: "https://platform.neuralspace.ai/api/nlu/v1/model/parse"

neuralspace-lang-detection-auth:
    ACCESS_TOKEN: ""
    neuralspace_lang_detect_url: "https://platform.neuralspace.ai/api/language-detection/v1/detect"

twitter-query:
    USER_HANDLE: ""
    RECENT_NUM_TWEETS: 
    RECENT_NUM_COMMENTS: 
    TWITTER_URL: ""

training-data:
    languages: ["en", "hi", "mr"]

control-precision:
    set-threshold: True
    threshold-roc: 

report: 
    download-report: True
    report-filename-pass-userhandle: "report1.txt"
    report-filename-pass-url: "report2.txt"

pass-userhandle: True

pass-tweet-url: True


